import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";

const Luciole_regular = localFont({
  src: '../../public/Fonts/Luciole-Regular.ttf',
  display: 'swap',
  variable: '--font-Luciole_Regular',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Luciole_regular.variable}`}>{children}</body>
    </html>
  );
}
