import type {Metadata} from "next";

import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import React from "react";
import Footer from "@/components/Footer";

const Luciole_regular = localFont({
    src: '../../public/Fonts/Luciole-Regular.ttf',
    display: 'swap',
    variable: '--font-Luciole_Regular',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${Luciole_regular.variable} font-Luciole_Regular`}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
