import type { Metadata } from "next";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
import React from "react";
import "./globals.css";

const Luciole_regular = localFont({
    src: '../../public/Fonts/Luciole-Regular.ttf',
    display: 'swap',
    variable: '--font-Luciole_Regular',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${Luciole_regular.variable} font-Luciole_Regular`}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
